"""Add Phase 3 Models Objectives and Logistics

Revision ID: 7074dcedfabe
Revises: 9af197f27d3e
Create Date: 2026-05-17 01:42:23.110093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7074dcedfabe'
down_revision: Union[str, Sequence[str], None] = '9af197f27d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plate_number', sa.Text(), nullable=False),
    sa.Column('vehicle_type', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('target_revenue', sa.Float(), nullable=True),
    sa.Column('target_volume', sa.Integer(), nullable=True),
    sa.Column('achieved_revenue', sa.Float(), nullable=True),
    sa.Column('achieved_volume', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('target_revenue', sa.Float(), nullable=True),
    sa.Column('target_volume', sa.Integer(), nullable=True),
    sa.Column('achieved_revenue', sa.Float(), nullable=True),
    sa.Column('achieved_volume', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=True),
    sa.Column('estimated_arrival', sa.Text(), nullable=True),
    sa.Column('actual_arrival', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('target_revenue', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('target_volume', sa.Integer(), nullable=True))
    with op.batch_alter_table('deliveries') as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_deliveries_route_id', 'routes', ['route_id'], ['id'])
    op.add_column('suppliers', sa.Column('target_revenue', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('target_volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'target_volume')
    op.drop_column('suppliers', 'target_revenue')
    with op.batch_alter_table('deliveries') as batch_op:
        batch_op.drop_constraint('fk_deliveries_route_id', type_='foreignkey')
        batch_op.drop_column('route_id')
    op.drop_column('clients', 'target_volume')
    op.drop_column('clients', 'target_revenue')
    op.drop_table('route_stops')
    op.drop_table('supplier_objectives')
    op.drop_table('routes')
    op.drop_table('client_objectives')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
