"""add_banking_module_models

Revision ID: 893940cce1e4
Revises: 593ba573fdc8
Create Date: 2026-05-19 00:34:10.350458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893940cce1e4'
down_revision: Union[str, Sequence[str], None] = '593ba573fdc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('iban', sa.Text(), nullable=True),
    sa.Column('swift_bic', sa.Text(), nullable=True),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('account_type', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bank_deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('deposit_date', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('cheque_number', sa.Text(), nullable=True),
    sa.Column('depositor_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('bank_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=False),
    sa.Column('dest_account_id', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dest_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('bank_withdrawals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('withdrawal_date', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('cheque_number', sa.Text(), nullable=True),
    sa.Column('beneficiary_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_withdrawals')
    op.drop_table('bank_transfers')
    op.drop_table('bank_deposits')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
